### ISSUE TITLE
Application stops when accessing the "Alla Fragen" menu

### ISSUE THREAD

**Issue by rezamusic881** [jfilter/frag-den-staat-app#83] opened 2018-05-17 16:04 UTC
#### Expected behavior
Appropriately, the Application does not stop when the user opens a feature that is in the "Alle Anfragen menu"

#### Actual behavior
When I open the feature that is in "Alle Anfragen menu". Application stops automatically.

#### How to reproduce
1. Download application in F-droid or Playstore.
2. Run Application, then open "Alle Anfragen menu".
3. Click on the features provided by "Alle Anfragen menu". Then the app will stop automatically.

***
***

* Browser : Redmi Note 5A
* System Operating : 7.1.0 Nougat
* App Version : 0.8.1

#### Recording Of The Bug
https://youtu.be/Pf2hJ5lsAQA

**Comment by jfilter** [comment] 2018-08-14 21:10
Before, I also consider German or English language locales so I guess it was caused by your language setting. I think I fixed this for the next version but I am not 100% sure. Let's see. I will close this for now.

**Closed by jfilter** 2018-08-14 21:10 UTC
